---
title: "NBA Off-season Trade and Free-agent Signing"
author: "Chongxi Wang"
date: "May 2, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

### Problem Introduction
Every summer, every NBA manager needs to deal with trade and free-agent signing stuff. As we know, every team has the same salary cap. The goal of this project is to provide suggestion to pick best team and meanwhile keep the team under salary cap limitation.

The choices that NBA managers make are really significant to the development of a team. Some are pretty wonderful, for example Miami Heat signed Lebron James and Chris Bosh in 2012. Then they leaded Heat to a dynasty with 2 champions. Some are really bad, for example Nets traded for Kevin Garnett and Paul Pierce who were nearing the end of their careers by 3 first-round pick. Nets lost the hope of rebuilding and became one of worst team after this trade.

Therefore, within the league salary cap, it is vital significant for NBA managers to decide how to sign and trade to build a better team. This project would provide suggestion with the power of data science and machine learning.

### Current State
There are several problems related to this project in current data analysis in NBA field.

- Salary. Manager sometimes misestimate the value of a player. For example Chandler Parsons signed a $94M contract but he did not help the team at all.

- Game Result. Game result prediction is often not correct, which makes competitive aports amazing. In 2016 Finals, Warriors leaded 3-1 and the probability provided by analysts of that Warriors could win the champion was 99.7%. However, Cavaliers won the later 3 straight games and made the 0.3% come true.

- Team Quality. Most analysts use off/def efficiency or other high order value to judge the quality of a team. But those values are calculated from data of existing games. There is no standard to evalute a team if they did not play together. Only games like NBA 2K give the estimating score of a arbitrary team.

### Relevent Work
Every NBA team has data analysts. Every sports website has data analysts. They record every game, analyse every player, predict every series and so on. Thanks for their wonderful work so I can easily access those clean datasets. In addition, those experts also record and comment every trade, which would be the best benchmark for this project.

However, even those analysts did perfect work, there also exist trading and signing mistakes and wrong analysis. I would like to make full use of methods in data science and machine learning in my project and I am looking forward to give more accurate analysis.


## Problem Statement

### Research Objects
- Individual players, including their salary, performance.

- Teams, including their salary, team stats and every game of the team.

- Trades and free-agent contracts.

### subproblems
- Predict reasonable salary of a single player by the current salary and performance of 400+ players. Salary stands for ability to some extent. Salary should come from a combination of many aspects of performance, including basic stats and advanced stats. The problem is how to find a reasonable way to evaluate players.

- Predict the result of a single game by the stats and real result of 1200+ NBA regular games. Nobody can predict a game in a probability of 100%, which is the perfect part of competitive sports. However, better team usually defeat the worse one. The problem is how to train a game model to predict game result as precise as possible.

- Predict the quality of a team. The quality of a team is not the sum of individual abilities. This part of this project is to combine the whole, not only accumulate the stats, but also consider position and chemical reaction.

- Provide proposal on free-agent signing. There are hundreds of free-agent waiting to be signed. Certainly signing a superstar is the fastest way to improve your team quality. But salary cap and benches must be considered.

- Provide proposal on trade. Good trade can improve team quality. You can trade a superstar with many role players. You can adjust in-out balance. You can adjust the age structure and bring more energy. So question is, which choice is the best?


## implementation

### Data Source
- <https://www.basketball-reference.com>

### Part1: Salary Prediction
- At first I need to calculate player's standardized salary according to salary in 2017-18 season and the salary cap in the beginning of the contract. Because of the rapidly increasing of salary cap recent years, many early contracts signed several years ago become really cheap now. Five years ago, \$20M per year is the max contract while the number becomes \$35M now. The early contracts need converion.

- Then the problem becomes a simple regression problem. Random forest is a reasonable model, which use performance and salary of all players to train. After training, the model can take performance as input and predict the reasonable salary.

- Besides, difference in position should be considered. Players with 20Pts and 10Ast must be a pretty good PG while great C are supposed to get 20Pts and 10Reb. Therefore it is probably a good idea to train a model for each position. 

### Part2: Game Prediction
- At first I should collect the game log of 1230 games in 2017/18 regular season. The game log includes team perfprmance and opposite team performance.

- Then a classification model should be trained with the 1230 existing games. After training the model, given arbitrary two set of players, I can calculate the average performance, which is weighted by playing time, of the two teams and use the trained model tp predict game result.

### Part3: Team Quality Prediction
- The general idea of quantifing the team quality is to simulate great many games and predict the quality according the game result.

- At first I have to randomly select thousands of(even more if you have well-behaved computer) opposite team, which is formed by 10 palyers: five starters and five substitutes.

- Since I have trained a game result model, I can use it to predict the result of those great many simulated games. Team quality score will be generated by the win rate.

### Part4: Signing Proposal
- At first, a list of free-agents is necessary, which includes free agents, restricted free agents, and player with player option or team option.

- Then with the work of Part 1, reasonable salary of those free-agents can be predicted.

- According to the rest space of team's salary cap, I can simulate all of the situation of signing. In each situation, quality of the team after signing can be predicted by model in Part 3. The choice with the highest team quality will be adopted.

### Part5: Trade Proposal
- Since there are too many combinations of trade, users should manually design their own trade scheme.

- With the achievement in Part3, I can predict the change of team quality before and after the trade. The change of team quality will be the standard to judge trade.

- Draft picks in trade will be converted to player immediately, according to the performance of rookies in the past.

### Timeline
There are three periods of this project:

- Model training and adjusting. Model of salary prediction can be trained within one week. Model of game result prediction can be trained within one week. After training the initial model, I have to measure and adjusting the model until it works as expected.

- Model application. Signing and trade proposal parts are the application of the models. This period can be done in two weeks from the finish of model training.

- Deployment. After all the functions of this project works, I need to write reports and packaging the project, which would take more than two weeks. The final project will contain dozens of source and test Rscripts, several functional packages, several readme files and other reports.

## Prospect

### Potential Users
- NBA players. NBA players can use this project in two aspects.

    - Predict the reasonable salary for themselves.
  
    - Find themselves a appropriate team if they do not like the current team.

- NBA Managers. NBA managers can use this project in three aspects.

    - Predict the reasonable salary for a certain player.
    
    - Search all the free agent and find who to sign.
    
    - Evaluate a trade and decide to perform or not.

- NBA coach. NBA coaches can use this project in one aspect.

    - Select appropriate starters aiming at different opposite teams.
    
### Benefits for Users
- NBA players.

    - Using the result of this project, NBA players can avoid loss of signing a lower contract and avoid thinking themselves above bussiness.
    
    - NBA players can find a team which is perhaps not the hottest but appropriate to them. They can finally find a team where they can maximize their own value.

- NBA managers.

    - Using this project, NBA managers can avoid the mistake that give a player impractical contract for example signing Parsons with $94M.
    
    - This project can provide proposal to those NBA managers and help them to decide which free-agent to sign. The proposal is likely to be the optimal choice. Perhaps not the hottest and most expensive superstars, but the players who can improve the whole team as much as possible.
    
    - When NBA managers is hesitate in some trades, this project can tell them whether the trade is good or not and help them to avoid terrible trades.

- NBA coaches.

    - Every team plays different games. This project can predict who is the most appropriate facing different teams.

### Instruction
- NBA players.

    - NBA Players can use model in "Salary Prediction" part to predict their own salary by inputing their performance stats.
    
    - NBA Players can use model in "Team Quality Prediction" part to predict teams they might interest in by inputing their performance and the rest members in the team.

- NBA managers.

    - NBA managers can use model in "Salary Prediction" part to predict reasonable salary of a certain player by inputing the performance of him.

    - NBA managers can get suggestion in "Signing Proposal" part by inputing a NBA team.
    
    - NBA managers can get feedback on a certain trade in "Trade Proposal" part by inputing a trade scheme, including who in or out.

- NBA coaches.

    - NBA coaches can try their team and playing time for each player in "Game Prediction" part to know the possibility of winning a game.


## Project Success Measurement

### Model Performance
- Salary Model. Because the sample size is small, I will use bootstrapping to divide sample. The mean squared error in test set is the measurement for this regression model.

- Game Result Model. Because the sample size is small, I will use bootstrapping to divide sample. AUC can be the measurement of this 2-classification model.

### Project Performance
- Every player adjustment in each team is available and real team win rate for each team before and after signing and trade is recorded.

- This project can gives every signing or trade a score. comparing predicted score of signing or trade with change in real win rate would be the measurement of this project.

### Risk Analysis
- The risk in "Salary Prediction" part. There are two problems I should take to consideration. The first is that salary is not always reflect ability or performance, because some players perform bad after signing a big contract meanwhile some poorly-paid players work hard for their next contract and perform pretty good. The second is that the size of sample of salary-performance is really small, because there are only 400+ active NBA players. I can try past datasets and resampling methods to figure those problems.

- The risk in "Game Prediction" part. The first risk is that uncertainty of a game is pretty big. Two games with the same teams often have different results. Secondly, team's performance facing different opposite teams varies greatly. Therefore using average team performance to predict is not the optimal way.

- The risk in "Team Quality Prediction" part. As long as the result second part is good enough, team quality will be predicted fairly enough.

- The risk in "Signing Proposal" part. The biggest risk in this part is that players usually want higher contracts. The proposal provided by this project is calculated with the reasonable salary prediction which related to their real performance. However, the proposal is the ideal situation. The fact is that those weak teams must pay more to persuade good players to stay in a weak team, while those top teams should face the competition from other teams who can offer a bigger contract to a certain player.

- The risk in "Trade Proposal" part. This project provide suggestion based on that the manager wants to build a better team with higher quality. However, many teams is too weak to chase the championship. The first goal for those team is to rebuild. First round draft pick is more important than players for them. So the proposal from this project might not be appropriate for those teams in rebuilding.